---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app
  labels:
    app: redis-app

spec:
    
  replicas: 4
  selector:
    matchLabels:
      app: redis-app

  template:
    
    metadata:
      labels:
        app: redis-app

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - redis-app
            topologyKey: "kubernetes.io/hostname"

      containers:
      
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
